### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by anjasamar** [PhyreApps/PhyrePanel#4]
Error 500 when some act applying

**Comment by bobimicroweber** [comment]
Can you share more information about this?

**Comment by anjasamar** [comment]
So when we save the settings in the admin, in principle we save a parameter in the admin panel, an error 500 popup always appears, so, I have tried reinstalling up to 20 times, the results are the same as several Debian and Ubuntu, the results are the same.

**Comment by bobimicroweber** [comment]
There is no problem with this. I test it several times. i close the issue
